#!/usr/bin/env python3
"""Inline the woff2 fonts into src/index.template.html and write index.html.

The published page has to be a single self-contained file: artifact hosting
blocks requests to font CDNs, and a silent fallback would lose the woodtype
wordmark the whole design rests on.
"""

import base64
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).parent
TEMPLATE = ROOT / "src" / "index.template.html"
OUTPUT = ROOT / "index.html"
REMOTE_TEMPLATE = ROOT / "src" / "remote.template.html"
REMOTE_OUTPUT = ROOT / "remote.html"
# Artifact hosting supplies its own document skeleton, so that build gets the
# stylesheet plus the body contents and nothing else. Not committed.
FRAGMENT = ROOT / "dist" / "artifact.html"

ASSETS = {
    "__BEVAN_400__": "fonts/bevan-400.woff2",
    "__VETERAN__": "fonts/veteran-typewriter.woff2",
    # Generated by tools/make_frame.py; inlined for the same reason as the
    # fonts — the published page may not fetch anything off-host.
    "__FRAME__": "assets/frame.png",
    # The sting played when a round lands.
    "__STING__": "assets/sting.mp3",
}


def inline(html: str, source: str) -> str:
    """Swap every asset token in one template for its data URI."""
    for token, relative in ASSETS.items():
        if token not in html:
            continue                       # the remote uses only the fonts
        path = ROOT / relative
        if not path.exists():
            raise FileNotFoundError(f"{source}: missing asset {relative}")
        html = html.replace(token, base64.b64encode(path.read_bytes()).decode("ascii"))
    return html


def main() -> int:
    try:
        html = inline(TEMPLATE.read_text(encoding="utf-8"), TEMPLATE.name)
    except FileNotFoundError as exc:
        print(exc, file=sys.stderr)
        return 1

    OUTPUT.write_text(html, encoding="utf-8")
    print(f"wrote {OUTPUT.name} ({OUTPUT.stat().st_size / 1024:.0f} KB)")

    # The phone remote, served by server.py alongside the board.
    if REMOTE_TEMPLATE.exists():
        try:
            remote = inline(REMOTE_TEMPLATE.read_text(encoding="utf-8"), REMOTE_TEMPLATE.name)
        except FileNotFoundError as exc:
            print(exc, file=sys.stderr)
            return 1
        REMOTE_OUTPUT.write_text(remote, encoding="utf-8")
        print(f"wrote {REMOTE_OUTPUT.name} ({REMOTE_OUTPUT.stat().st_size / 1024:.0f} KB)")

    style = re.search(r"<style>.*?</style>", html, re.S)
    body = re.search(r"<body>(.*)</body>", html, re.S)
    if not style or not body:
        print("could not locate <style> and <body> to build the fragment", file=sys.stderr)
        return 1
    FRAGMENT.parent.mkdir(exist_ok=True)
    FRAGMENT.write_text(style.group(0) + "\n" + body.group(1).strip() + "\n", encoding="utf-8")
    print(f"wrote {FRAGMENT.relative_to(ROOT)} ({FRAGMENT.stat().st_size / 1024:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
